# Generated by Django 5.2.13 on 2026-05-02 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0022_learningsession_target_six_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('experiment', 'Экспериментальная (EORA)'), ('control', 'Контрольная')], default='control', help_text='Тип группы: экспериментальная или контрольная', max_length=16)),
                ('test_type', models.CharField(choices=[('pre', 'Входной тест'), ('post', 'Итоговый тест')], help_text='Входной или итоговый тест', max_length=8)),
                ('score_percent', models.FloatField(help_text='Результат в процентах (0–100)')),
                ('correct_tasks', models.PositiveIntegerField(default=0, help_text='Количество правильно решённых задач')),
                ('max_tasks', models.PositiveIntegerField(default=5, help_text='Всего задач в тесте')),
                ('participant_code', models.CharField(blank=True, help_text='Анонимный код участника (например, Ученик-01)', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_group', models.ForeignKey(blank=True, help_text='Группа апробации (необязательно)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_test_results', to='learning.studygroup')),
            ],
            options={
                'verbose_name': 'Результат внешнего теста',
                'verbose_name_plural': 'Результаты внешних тестов',
                'ordering': ['group_type', 'test_type', 'created_at'],
            },
        ),
    ]
