# Generated by Django 5.2.3 on 2025-12-27 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание СК для ученика')),
                ('image', models.ImageField(upload_to='ks/')),
                ('show_zones_by_default', models.BooleanField(default=True, help_text='Показывать зоны по умолчанию')),
                ('typical_task_title', models.CharField(blank=True, help_text="Название типа задач (например, 'Найти значения физических величин, характеризующих равномерное и неравномерное движение')", max_length=255)),
                ('typical_task_description', models.TextField(blank=True, help_text='Описание: с какой целью и в каких ситуациях применяется СК')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Система знаний',
                'verbose_name_plural': 'Системы знаний',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemaElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('point', 'Точка'), ('vector', 'Вектор'), ('line', 'Линия'), ('arc', 'Дуга'), ('text', 'Текст'), ('axis', 'Ось координат'), ('body', 'Тело'), ('trajectory', 'Траектория')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='CSS класс иконки или emoji', max_length=50)),
                ('default_props', models.JSONField(blank=True, default=dict, help_text='Свойства по умолчанию (цвет, размер, ...)')),
            ],
            options={
                'verbose_name': 'Тип элемента схемы',
                'verbose_name_plural': 'Типы элементов схемы',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='KSCloze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(help_text='HTML с тегами <gap id="..."></gap> для пропусков')),
                ('use_global_options', models.BooleanField(default=False, help_text='Общий пул вариантов для всех пропусков')),
                ('order', models.PositiveIntegerField(default=1)),
                ('ks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clozes', to='learning.knowledgesystem')),
            ],
            options={
                'verbose_name': 'Cloze-тест',
                'verbose_name_plural': 'Cloze-тесты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KSClozeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('cloze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning.kscloze')),
            ],
            options={
                'verbose_name': 'Вариант Cloze',
                'verbose_name_plural': 'Варианты Cloze',
            },
        ),
        migrations.CreateModel(
            name='KSClozeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_id', models.CharField(help_text='ID из <gap id="...">', max_length=50)),
                ('cloze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='learning.kscloze')),
                ('correct_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_for_gaps', to='learning.ksclozeoption')),
                ('options', models.ManyToManyField(blank=True, help_text='Варианты для этого пропуска (если не глобальный пул)', related_name='for_gaps', to='learning.ksclozeoption')),
            ],
            options={
                'verbose_name': 'Пропуск Cloze',
                'verbose_name_plural': 'Пропуски Cloze',
            },
        ),
        migrations.CreateModel(
            name='KSZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, help_text='Метка зоны (для админки)', max_length=100)),
                ('ks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='learning.knowledgesystem')),
            ],
            options={
                'verbose_name': 'Зона СК',
                'verbose_name_plural': 'Зоны СК',
            },
        ),
        migrations.CreateModel(
            name='KSQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Формулировка вопроса')),
                ('order', models.PositiveIntegerField(default=1)),
                ('multiple_allowed', models.BooleanField(default=True, help_text='Можно выбрать несколько зон')),
                ('ks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.knowledgesystem')),
                ('correct_zones', models.ManyToManyField(blank=True, related_name='correct_for_questions', to='learning.kszone')),
            ],
            options={
                'verbose_name': 'Вопрос СК',
                'verbose_name_plural': 'Вопросы СК',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('comprehension', 'Осмысление СК'), ('typical_task', 'Формулировка типовой задачи'), ('task_list', 'Список задач'), ('difficulty_assessment', 'Оценка трудности'), ('solving_easy', 'Решение (вариант Лёгкое)'), ('solving_medium', 'Решение (вариант Непростое)'), ('solving_hard', 'Решение (вариант Трудное)'), ('method_composition', 'Составление метода'), ('step_by_step', 'Пооперационный контроль'), ('verbalization', 'Проговаривание метода'), ('compact_solving', 'Свёрнутое решение'), ('diagnostic', 'Диагностическая работа'), ('completed', 'Завершено')], default='comprehension', max_length=30)),
                ('difficulty_choice', models.CharField(blank=True, choices=[('easy', 'Лёгкое'), ('medium', 'Непростое'), ('hard', 'Трудное')], help_text='Выбор ученика: насколько трудным показалось задание', max_length=10)),
                ('comprehension_passed', models.BooleanField(default=False)),
                ('comprehension_score', models.FloatField(default=0)),
                ('tasks_solved_count', models.PositiveIntegerField(default=0)),
                ('tasks_correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_attempts_in_row', models.PositiveIntegerField(default=0, help_text='Количество неправильных ответов подряд')),
                ('score_percent', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.knowledgesystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия обучения',
                'verbose_name_plural': 'Сессии обучения',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='learning.learningsession')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='SolutionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Название метода (например, 'Метод решения задач на равномерное и неравномерное движение')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Общее описание метода')),
                ('ks', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution_method', to='learning.knowledgesystem')),
            ],
            options={
                'verbose_name': 'Метод решения',
                'verbose_name_plural': 'Методы решения',
            },
        ),
        migrations.CreateModel(
            name='SolutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Порядковый номер шага (1-10)')),
                ('title', models.CharField(help_text='Краткое название действия', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Подробное описание действия')),
                ('hint', models.TextField(blank=True, help_text='Подсказка ученику')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learning.solutionmethod')),
            ],
            options={
                'verbose_name': 'Шаг метода',
                'verbose_name_plural': 'Шаги метода',
                'ordering': ['method', 'order'],
                'unique_together': {('method', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SubjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning.schoolclass')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['school_class__number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Порядок в списке')),
                ('title', models.CharField(help_text='Краткое название задачи', max_length=255)),
                ('text', models.TextField(help_text='Полный текст условия задачи')),
                ('correct_answer', models.FloatField(blank=True, help_text='Числовой правильный ответ', null=True)),
                ('answer_unit', models.CharField(blank=True, help_text='Единица измерения (м/с, км, с, ...)', max_length=50)),
                ('answer_tolerance', models.FloatField(default=1.0, help_text='Допустимая погрешность в процентах')),
                ('correct_answer_text', models.CharField(blank=True, help_text='Текстовый правильный ответ (если не числовой)', max_length=255)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Очень лёгкая'), (2, 'Лёгкая'), (3, 'Средняя'), (4, 'Сложная'), (5, 'Очень сложная')], default=3)),
                ('solution_summary', models.TextField(blank=True, help_text='Краткое решение (формула + ответ)')),
                ('solution_detailed', models.TextField(blank=True, help_text='Развёрнутое решение')),
                ('solution_image', models.ImageField(blank=True, help_text='Изображение с решением', null=True, upload_to='solutions/')),
                ('ks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.knowledgesystem')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['ks', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SchemaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название шаблона', max_length=100)),
                ('is_reference', models.BooleanField(default=False, help_text='Это эталонная схема для сравнения')),
                ('is_starter', models.BooleanField(default=False, help_text='Это начальная заготовка для ученика')),
                ('data', models.JSONField(default=dict, help_text='JSON с элементами схемы')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_templates', to='learning.task')),
            ],
            options={
                'verbose_name': 'Шаблон схемы',
                'verbose_name_plural': 'Шаблоны схем',
            },
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_numeric', models.FloatField(blank=True, null=True)),
                ('answer_text', models.CharField(blank=True, max_length=255)),
                ('answer_image', models.ImageField(blank=True, help_text='Фото решения ученика', null=True, upload_to='student_solutions/')),
                ('schema_data', models.JSONField(blank=True, default=dict, help_text='Схема, нарисованная учеником')),
                ('is_correct', models.BooleanField(null=True)),
                ('feedback', models.TextField(blank=True, help_text='Обратная связь системы')),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Очень легко'), (2, 'Легко'), (3, 'Средне'), (4, 'Сложно'), (5, 'Очень сложно')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Время на решение в секундах')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attempts', to='learning.learningsession')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.task')),
            ],
            options={
                'verbose_name': 'Попытка решения',
                'verbose_name_plural': 'Попытки решения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(blank=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='step_attempts/')),
                ('chose_system_variant', models.BooleanField(default=False, help_text='Ученик выбрал эталонный вариант вместо своего')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.solutionstep')),
                ('task_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_attempts', to='learning.taskattempt')),
            ],
            options={
                'verbose_name': 'Попытка по шагу',
                'verbose_name_plural': 'Попытки по шагам',
                'ordering': ['task_attempt', 'step__order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.subjectsection')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['section__order', 'order'],
            },
        ),
        migrations.AddField(
            model_name='knowledgesystem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_systems', to='learning.topic'),
        ),
        migrations.CreateModel(
            name='TaskSolutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Результат выполнения этого шага для данной задачи')),
                ('image', models.ImageField(blank=True, help_text='Изображение (схема, график) для этого шага', null=True, upload_to='task_steps/')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to='learning.solutionstep')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_steps', to='learning.task')),
            ],
            options={
                'verbose_name': 'Шаг решения задачи',
                'verbose_name_plural': 'Шаги решения задач',
                'ordering': ['task', 'step__order'],
                'unique_together': {('task', 'step')},
            },
        ),
    ]
