# Generated by Django 5.2.3 on 2026-01-08 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название элемента', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Описание для подсказки')),
                ('svg_icon', models.TextField(blank=True, help_text='SVG-код иконки для палитры (маленький, ~24x24)')),
                ('svg_template', models.TextField(blank=True, help_text='SVG-код для отрисовки на холсте')),
                ('default_props', models.JSONField(blank=True, default=dict, help_text='Свойства: {color, strokeWidth, fontSize, ...}')),
                ('editable_props', models.JSONField(blank=True, default=list, help_text="Список редактируемых свойств: ['color', 'label', 'size']")),
                ('is_system', models.BooleanField(default=False, help_text='Системный элемент (нельзя удалить/изменить)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, help_text='Теги через запятую: скорость, механика, вектор', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schema_elements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Элемент схемы',
                'verbose_name_plural': 'Элементы схем',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchemaElementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji или иконка', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False, help_text='Системная категория (нельзя удалить)')),
            ],
            options={
                'verbose_name': 'Категория элементов',
                'verbose_name_plural': 'Категории элементов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='JSON схемы ученика')),
                ('similarity_score', models.FloatField(blank=True, help_text='Оценка похожести на эталон (0-1)', null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Обратная связь')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(blank=True, help_text='К какому шагу метода относится схема', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_schemas', to='learning.solutionstep')),
                ('task_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='learning.taskattempt')),
            ],
            options={
                'verbose_name': 'Схема ученика',
                'verbose_name_plural': 'Схемы учеников',
            },
        ),
        migrations.DeleteModel(
            name='SchemaElementType',
        ),
        migrations.RemoveField(
            model_name='schematemplate',
            name='is_reference',
        ),
        migrations.RemoveField(
            model_name='schematemplate',
            name='is_starter',
        ),
        migrations.AddField(
            model_name='schematemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='schematemplate',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Автогенерируемое превью схемы', null=True, upload_to='schema_previews/'),
        ),
        migrations.AddField(
            model_name='schematemplate',
            name='template_type',
            field=models.CharField(choices=[('reference', 'Эталонная схема'), ('starter', 'Начальная заготовка'), ('hint', 'Подсказка')], default='reference', max_length=20),
        ),
        migrations.AddField(
            model_name='schematemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='schematemplate',
            name='data',
            field=models.JSONField(default=dict, help_text='JSON: {width, height, elements: [{type, x, y, props, ...}]}'),
        ),
        migrations.AddField(
            model_name='schemaelement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='learning.schemaelementcategory'),
        ),
    ]
