# Generated by Django 5.2.3 on 2026-01-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_update_comprehension_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionstep',
            name='hide_title_in_composition',
            field=models.BooleanField(default=False, help_text='Скрыть название в этапе составления метода (ученик должен его заполнить)'),
        ),
    ]
