# Generated by Django 5.2.3 on 2026-01-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_add_step_attempt_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksolutionstep',
            name='schema_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON с данными схемы (элементы, позиции и т.д.)'),
        ),
        migrations.AddField(
            model_name='tasksolutionstep',
            name='step_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('schema', 'Схема (рисование)')], default='text', help_text='Тип шага: текстовый ответ или рисование схемы', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasksolutionstep',
            name='content',
            field=models.TextField(blank=True, help_text='Результат выполнения этого шага для данной задачи (текст)'),
        ),
    ]
