# Generated by Django 5.2.3 on 2026-03-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_add_learning_path_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesystem',
            name='typical_task_title',
            field=models.CharField(blank=True, help_text="Название типа задач (например, 'Найти значения физических величин, характеризующих равномерное и неравномерное движение')", max_length=255),
        ),
        migrations.AlterField(
            model_name='solutionmethod',
            name='title',
            field=models.CharField(help_text="Название метода (например, 'Метод решения задач на равномерное и неравномерное движение')", max_length=255),
        ),
        migrations.AlterField(
            model_name='tasksolutionstep',
            name='step_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('text_pick', 'Выбор ответа из текста'), ('symbol', 'Обозначение величины (Дано)'), ('schema', 'Схема (рисование)')], default='text', help_text='Тип шага: текстовый ответ или рисование схемы', max_length=10),
        ),
    ]
