# Generated by Django 5.2.3 on 2026-04-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_learningsession_scenario_two_errors_and_taskattempt_teacher_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='step_by_step_completions',
            field=models.PositiveIntegerField(default=0, help_text='Сколько раз ученик успешно завершил пооперационный контроль'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='step_error_history',
            field=models.JSONField(blank=True, default=dict, help_text='История ошибок по шагам: {step_order: error_count}'),
        ),
    ]
