# Generated by Django 5.2.3 on 2026-04-13 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_add_scaffolding_and_tracking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='mastery_percent',
            field=models.FloatField(blank=True, help_text='Итоговый %% усвоения (автоматика + отметка + активность); до проверки — null', null=True),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='teacher_final_mark',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Отметка учителя 2–5 за итоговую задачу после проверки', null=True),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='teacher_grade_2_5',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Выставленная учителем отметка 2–5 за эту попытку', null=True),
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: «7 А — фокус весна 2026»', max_length=120)),
                ('letter', models.CharField(blank=True, default='', help_text='Буква класса (А, Б, …)', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='Учитель-организатор, ведущий группу', on_delete=django.db.models.deletion.CASCADE, related_name='owned_study_groups', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, help_text='Необязательно: привязка к классу из структуры курса (7/8/9)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='learning.schoolclass')),
            ],
            options={
                'verbose_name': 'Группа апробации',
                'verbose_name_plural': 'Группы апробации',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=False, help_text='Если True — ученик должен сменить пароль в приложении')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль ЭОР',
                'verbose_name_plural': 'Профили ЭОР',
            },
        ),
        migrations.CreateModel(
            name='StudyGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='learning.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник группы',
                'verbose_name_plural': 'Участники групп',
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='uniq_studygroup_membership')],
            },
        ),
    ]
