# Generated by Django 4.2.30 on 2026-05-23 13:45

from django.db import migrations, models
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_learningsession_target_six_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='illustration',
            field=models.ImageField(blank=True, help_text='Квадратная иллюстрация к задаче (для визуализации сценария)', null=True, upload_to='tasks/illustrations/'),
        ),
        migrations.AlterField(
            model_name='knowledgesystem',
            name='comprehension_image',
            field=models.ImageField(blank=True, help_text='Изображение таблицы для этапа осмысления (с зонами)', null=True, upload_to='ks/comprehension/', validators=[learning.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='knowledgesystem',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное изображение Системы Знаний', null=True, upload_to='ks/', validators=[learning.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='schematemplate',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Автогенерируемое превью схемы', null=True, upload_to='schema_previews/', validators=[learning.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='stepattempt',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='step_attempts/', validators=[learning.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='task',
            name='solution_image',
            field=models.ImageField(blank=True, help_text='Изображение с решением', null=True, upload_to='solutions/', validators=[learning.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='taskattempt',
            name='answer_image',
            field=models.ImageField(blank=True, help_text='Фото решения ученика (макс. 5 MB, форматы: JPG, PNG, GIF, WebP)', null=True, upload_to='student_solutions/', validators=[learning.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='taskattemptimage',
            name='image',
            field=models.ImageField(upload_to='student_solutions/', validators=[learning.models.validate_image_file]),
        ),
    ]
