# Generated by Django 4.2.30 on 2026-05-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_task_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='compact_fail_streak',
            field=models.PositiveSmallIntegerField(default=0, help_text='Сколько свёрнутых вариантов подряд не пройдено чисто (для назначения полного контроля)'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='control_choice_offered',
            field=models.BooleanField(default=False, help_text='Предлагали ли ученику выбор «контрольная / ещё задача» перед последней задачей'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='last_task_clean',
            field=models.BooleanField(default=True, help_text='Прошлая задача пройдена без срабатывания опоры (для расчёта переноса уровня)'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='support_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Уровень опоры: 0 — самостоятельно, 1 — свёрнутый вариант, 2 — пооперационный контроль'),
        ),
    ]
