# Generated by Django 5.2.3 on 2026-01-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_schemaelement_schemaelementcategory_studentschema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksclozeoption',
            name='cloze',
        ),
        migrations.AlterModelOptions(
            name='kscloze',
            options={'ordering': ['ks', 'order'], 'verbose_name': 'Текст с пропусками', 'verbose_name_plural': 'Тексты с пропусками'},
        ),
        migrations.AlterModelOptions(
            name='ksquestion',
            options={'ordering': ['ks', 'order'], 'verbose_name': 'Вопрос Системы Знаний', 'verbose_name_plural': 'Вопросы Системы Знаний'},
        ),
        migrations.RemoveField(
            model_name='kscloze',
            name='html',
        ),
        migrations.RemoveField(
            model_name='kscloze',
            name='use_global_options',
        ),
        migrations.RemoveField(
            model_name='ksquestion',
            name='multiple_allowed',
        ),
        migrations.AddField(
            model_name='knowledgesystem',
            name='comprehension_image',
            field=models.ImageField(blank=True, help_text='Изображение таблицы для этапа осмысления (с зонами)', null=True, upload_to='ks/comprehension/'),
        ),
        migrations.AddField(
            model_name='knowledgesystem',
            name='comprehension_pass_threshold',
            field=models.PositiveIntegerField(default=85, help_text='Минимальный процент правильных ответов для прохождения осмысления'),
        ),
        migrations.AddField(
            model_name='kscloze',
            name='blanks',
            field=models.JSONField(default=list, help_text='Пропуски: [{"position": 0, "correct": "слово"}, ...]'),
        ),
        migrations.AddField(
            model_name='kscloze',
            name='distractors',
            field=models.JSONField(default=list, help_text='Слова-отвлекатели: ["неверное1", "неверное2", ...]'),
        ),
        migrations.AddField(
            model_name='kscloze',
            name='marked_text',
            field=models.TextField(blank=True, default='', help_text='Текст с маркерами {{0}}, {{1}}, ... для пропусков'),
        ),
        migrations.AddField(
            model_name='kscloze',
            name='original_text',
            field=models.TextField(blank=True, default='', help_text='Исходный текст до разметки пропусков'),
        ),
        migrations.AddField(
            model_name='ksquestion',
            name='correct_answer_text',
            field=models.CharField(blank=True, help_text="Правильный текстовый ответ (для типа 'text')", max_length=500),
        ),
        migrations.AddField(
            model_name='ksquestion',
            name='fuzzy_match',
            field=models.BooleanField(default=False, help_text='Разрешить похожие ответы (игнорировать регистр, пробелы)'),
        ),
        migrations.AddField(
            model_name='ksquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Варианты: [{"text": "Вариант 1", "is_correct": false}, ...]'),
        ),
        migrations.AddField(
            model_name='ksquestion',
            name='type',
            field=models.CharField(choices=[('text', 'Открытый ответ'), ('single', 'Выбор одного варианта'), ('multiple', 'Множественный выбор'), ('match', 'Соответствие (выбор зон)')], default='single', help_text='Тип вопроса', max_length=20),
        ),
        migrations.AddField(
            model_name='ksquestion',
            name='zones',
            field=models.ManyToManyField(blank=True, help_text='Зоны, которые подсвечиваются при этом вопросе', related_name='questions', to='learning.kszone'),
        ),
        migrations.AlterField(
            model_name='knowledgesystem',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное изображение Системы Знаний', null=True, upload_to='ks/'),
        ),
        migrations.AlterField(
            model_name='ksquestion',
            name='correct_zones',
            field=models.ManyToManyField(blank=True, help_text="Правильные зоны (для типа 'match')", related_name='correct_for_questions', to='learning.kszone'),
        ),
        migrations.CreateModel(
            name='ComprehensionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('score_percent', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_attempts', to='learning.learningsession')),
            ],
            options={
                'verbose_name': 'Попытка осмысления',
                'verbose_name_plural': 'Попытки осмысления',
            },
        ),
        migrations.CreateModel(
            name='ClozeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('correct_positions', models.JSONField(default=list)),
                ('wrong_positions', models.JSONField(default=list)),
                ('score', models.FloatField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='learning.kscloze')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloze_answers', to='learning.comprehensionattempt')),
            ],
            options={
                'verbose_name': 'Ответ на текст с пропусками',
                'verbose_name_plural': 'Ответы на тексты с пропусками',
                'unique_together': {('attempt', 'cloze')},
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=500)),
                ('answer_index', models.IntegerField(blank=True, null=True)),
                ('answer_indices', models.JSONField(blank=True, default=list)),
                ('answer_zone_ids', models.JSONField(blank=True, default=list)),
                ('is_correct', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='learning.comprehensionattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='learning.ksquestion')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='KSClozeGap',
        ),
        migrations.DeleteModel(
            name='KSClozeOption',
        ),
    ]
