# Generated by Django 5.2.3 on 2026-01-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_add_hide_title_in_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepattempt',
            name='final_answer',
            field=models.TextField(blank=True, help_text='Финальный вариант ответа (после выбора ученика)'),
        ),
        migrations.AddField(
            model_name='stepattempt',
            name='is_correct',
            field=models.BooleanField(blank=True, help_text='Результат автоматической проверки (null = не проверено или выбор варианта)', null=True),
        ),
        migrations.AddField(
            model_name='stepattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
