# Generated by Django 5.2.3 on 2026-02-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_add_typical_task_formulation_to_learningsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='typical_task_correct',
            field=models.BooleanField(blank=True, help_text='Правильно ли ученик выбрал типовую задачу', null=True),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='typical_task_formulation',
            field=models.TextField(blank=True, help_text='(устаревшее) Формулировка типовой задачи, введенная учеником'),
        ),
        migrations.CreateModel(
            name='TypicalTaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст варианта ответа')),
                ('is_correct', models.BooleanField(default=False, help_text='Является ли этот вариант правильным')),
                ('order', models.PositiveIntegerField(default=1, help_text='Порядок отображения')),
                ('explanation', models.TextField(blank=True, help_text='Пояснение, почему вариант правильный/неправильный (показывается после ответа)')),
                ('ks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typical_task_options', to='learning.knowledgesystem')),
            ],
            options={
                'verbose_name': 'Вариант типовой задачи',
                'verbose_name_plural': 'Варианты типовой задачи',
                'ordering': ['ks', 'order'],
            },
        ),
        migrations.AddField(
            model_name='learningsession',
            name='typical_task_option',
            field=models.ForeignKey(blank=True, help_text='Выбранный учеником вариант типовой задачи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='learning.typicaltaskoption'),
        ),
    ]
