# Generated by Django 5.2.3 on 2026-02-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_populate_typical_task_options_ks1'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesystem',
            name='typical_task_cloze_blanks',
            field=models.JSONField(blank=True, default=list, help_text='Пропуски: [{"position": 0, "correct": "Описать"}, ...]'),
        ),
        migrations.AddField(
            model_name='knowledgesystem',
            name='typical_task_cloze_distractors',
            field=models.JSONField(blank=True, default=list, help_text='Слова-отвлекатели: ["неверное1", "неверное2", ...]'),
        ),
        migrations.AddField(
            model_name='knowledgesystem',
            name='typical_task_cloze_text',
            field=models.TextField(blank=True, default='', help_text='Текст с маркерами {{0}}, {{1}}, ... для пропусков. Пример: "{{0}} движение и {{1}} величины"'),
        ),
    ]
