# Generated by Django 5.2.3 on 2026-02-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_populate_typical_task_cloze_ks1'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='current_task_index',
            field=models.PositiveIntegerField(default=0, help_text='Индекс текущей задачи в последовательности (0-based)'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='learning_path',
            field=models.CharField(blank=True, choices=[('self_solve', 'Попробую решить самостоятельно'), ('review_example', 'Хорошо бы сначала разобрать пример'), ('discuss_and_review', 'Нужно обсудить способ решения и разобрать пример')], help_text='Выбранный порядок работы: самостоятельно / разобрать пример / обсудить и разобрать', max_length=30),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='target_tasks_count',
            field=models.PositiveIntegerField(default=5, help_text='Целевое количество задач для решения в этой сессии'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='current_stage',
            field=models.CharField(choices=[('comprehension', 'Осмысление СК'), ('typical_task', 'Формулировка типовой задачи'), ('task_preview', 'Ознакомление с заданием'), ('learning_path_choice', 'Выбор порядка работы'), ('task_list', 'Список задач'), ('difficulty_assessment', 'Оценка трудности'), ('solving_easy', 'Решение (вариант Лёгкое)'), ('solving_medium', 'Решение (вариант Непростое)'), ('solving_hard', 'Решение (вариант Трудное)'), ('method_composition', 'Составление метода'), ('step_by_step', 'Пооперационный контроль'), ('verbalization', 'Проговаривание метода'), ('compact_solving', 'Свёрнутое решение'), ('diagnostic', 'Диагностическая работа'), ('completed', 'Завершено')], default='comprehension', max_length=30),
        ),
    ]
