# Generated by Django 5.2.3 on 2026-03-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_alter_knowledgesystem_typical_task_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksolutionstep',
            name='step_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('text_pick', 'Выбор ответа из текста'), ('symbol', 'Обозначение величины (Дано)'), ('boolean', 'Ответ да/нет'), ('schema', 'Схема (рисование)')], default='text', help_text='Тип шага: текстовый ответ или рисование схемы', max_length=10),
        ),
    ]
